# Generated by Django 4.2.4 on 2023-08-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('W', 'Waiting'), ('C', 'Completed')], default='Pending', max_length=50),
        ),
    ]
