# Generated by Django 4.2.4 on 2023-08-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_tax_remove_order_total_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Ordered'), ('P', 'Paid'), ('C', 'Cancelled'), ('D', 'Completed')], default='Ordered', max_length=50),
        ),
    ]
